language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
     - PRETTYNAME="Adafruit IO Arduino Library"


before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/brentru/travis-ci-arduino/add-m4-airlift-target/install.sh)
   - cd $HOME/arduino_ide/libraries/
   - wget https://github.com/adafruit/WiFiNINA/archive/1.3.0.zip && unzip 1.3.0.zip && rm 1.3.0.zip
   - cd /home/travis/build/adafruit/Adafruit_IO_Arduino

install:
    - arduino --install-library "Adafruit IO Arduino","Adafruit MQTT Library","ArduinoHttpClient"
    - arduino --install-library "Adafruit Unified Sensor","Adafruit NeoPixel","DHT sensor library", "Ethernet"

script:
    # build SAMD target
    - build_platform m4wifi
    # build ESP8266 target
    - build_platform esp8266
