language: c
sudo: false

# Blacklist
branches:
  except:
    - gh-pages

env:
  global:
     - PRETTYNAME="Adafruit IO Arduino Library"


before_install:
   - source <(curl -SLs https://raw.githubusercontent.com/brentru/travis-ci-arduino/add-m4-airlift-target/install.sh)

install:
    - arduino --install-library "Adafruit IO Arduino","Adafruit MQTT Library","ArduinoHttpClient"
    - arduino --install-library "Adafruit Unified Sensor","Adafruit NeoPixel","DHT sensor library"

script:
    # build ESP8266 target
    - build_platform esp8266
    # build SAMD target
    - arduino --install-library "WiFi101", "Ethernet"
    - build_platform m4wifi
